import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CloukitStoryModule, CloukitStoryService } from '@cloukit/story';
import { CloukitIconModule } from '../../../projects/cloukit/icon/src/public_api';
import { DemoComponent } from './demo.component';
import { Story00Component } from './stories/story-00-single-layer-icons';
import { Story01Component } from './stories/story-01-different-sizes';
import { Story02Component } from './stories/story-02-stacked-multi-layer-icons';
import { Story03Component } from './stories/story-03-masked-multi-layer-icons';
import { Story04Component } from './stories/story-04-transformed-icons';
import { Story05Component } from './stories/story-05-register-custom-icon';

@NgModule({
  declarations: [
    DemoComponent,
    Story00Component,
    Story01Component,
    Story02Component,
    Story03Component,
    Story04Component,
    Story05Component,
  ],
  exports: [
    DemoComponent
  ],
  imports: [
    CommonModule,
    CloukitIconModule,
    CloukitStoryModule,
  ],
  providers: [ ],
  bootstrap: [ ],
})
export class DemoModule {
  constructor(private cloukitStoryService: CloukitStoryService) {
    //
    // INITIALIZE STORY SOURCES
    //
    let baseUrl = '/';
    if (document.getElementsByTagName('base') && document.getElementsByTagName('base')[0]) {
      // in Karma tests we do not have that dom element present
      baseUrl = document.getElementsByTagName('base')[0].href;
    }
    // File is auto generated by build chain 'yarn pre'
    const storySourceJsonUrl = `${baseUrl}assets/demo-stories-source.json`;
    this.cloukitStoryService.loadStoryJson(storySourceJsonUrl);
  }
}
