import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CloukitStoryModule, CloukitStoryService } from '@cloukit/story';
import { CloukitIconModule } from '../index';
import { DemoComponent } from './demo.component';
import { Story00Component } from './stories/story-00-single-layer-icons';
import { Story01Component } from './stories/story-01-different-sizes';
import { Story02Component } from './stories/story-02-stacked-multi-layer-icons';
import { Story03Component } from './stories/story-03-masked-multi-layer-icons';
import { Story04Component } from './stories/story-04-transformed-icons';
import { Story05Component } from './stories/story-05-register-custom-icon';

@NgModule({
  declarations: [
    DemoComponent,
    Story00Component,
    Story01Component,
    Story02Component,
    Story03Component,
    Story04Component,
    Story05Component,
  ],
  exports: [
    DemoComponent
  ],
  imports: [
    CommonModule,
    CloukitIconModule,
    CloukitStoryModule,
  ],
  providers: [ ],
  bootstrap: [ ],
})
export class DemoModule {
  constructor(private cloukitStoryService: CloukitStoryService) {
    //
    // INITIALIZE STORY SOURCES
    //
    const baseUrl = document.getElementsByTagName('base')[0].href;
    const storySourceJsonUrl = `${baseUrl}assets/demoStoriesSource.json`; // File is auto generated by build chain!
    this.cloukitStoryService.loadStoryJson(storySourceJsonUrl);
  }
}
